# numpy practice session

In [71]:
#pip install numpy

In [72]:
# import this library in jupyter notebook
import numpy as np

# creating an array using numpy

In [73]:
items=np.array(['oil', 'paste', 'soap'])
items

array(['oil', 'paste', 'soap'], dtype='<U5')

In [74]:
price = np.array([530,185,125])
price

array([530, 185, 125])

In [75]:
type(price)

numpy.ndarray

In [76]:
len(price)

3

In [77]:
type(items)

numpy.ndarray

In [78]:
len(items)

3

In [79]:
price[1]

185

In [80]:
items[2]

'soap'

In [81]:
price.mean()

280.0

In [82]:
items[0:]

array(['oil', 'paste', 'soap'], dtype='<U5')

In [83]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [84]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [85]:
#ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [86]:
#empty
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [87]:
#range
np.arange(12)
#last element is inclusive

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [88]:
#specify the range
np.arange(3, 33)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [89]:
# a range with intervals
np.arange(6, 42, 3)

array([ 6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [90]:
#table of 55
np.arange(55, 605, 55)

array([ 55, 110, 165, 220, 275, 330, 385, 440, 495, 550])

In [91]:
np.linspace(0, 120, num=10)

array([  0.        ,  13.33333333,  26.66666667,  40.        ,
        53.33333333,  66.66666667,  80.        ,  93.33333333,
       106.66666667, 120.        ])

In [92]:
# specify data types
np.ones(20, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [93]:
# specify data types
np.ones(20, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

# Array functions

In [94]:
a= np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [95]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [96]:
b=np.array([10.2,3.4, 53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [97]:
np.concatenate((a,b))

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [98]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [99]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# 2D Arrays

In [100]:
a=np.array([[2,4,6,8,10],[1,3,5,7,9]])
a

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [101]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [102]:
#concatenate 2D array
c=np.concatenate((a,b))
c

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [103]:
c.sort()
c

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [104]:
len(c)

4

In [105]:
type(c)

numpy.ndarray

In [106]:
np.concatenate((a,b), axis=1)

array([[ 2,  4,  6,  8, 10,  1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9,  6,  7,  8,  9, 10]])

In [107]:
np.concatenate((a,b), axis=0)

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# 3D Array

In [108]:
a=np.array([[[1,2,3],[2,4,5],[7,8,6]]])
a

array([[[1, 2, 3],
        [2, 4, 5],
        [7, 8, 6]]])

In [109]:
#to find the number of dimensions/axis
a.ndim

3

In [110]:
b=np.array([[[1,2,3],[3,2,1]],
            [[3,4,5],[5,4,3]],
            [[6,7,8],[8,7,6]]])


In [111]:
b.ndim

3

In [112]:
#size of array no. of elements
a.size

9

In [113]:
b.size

18

In [114]:
a

array([[[1, 2, 3],
        [2, 4, 5],
        [7, 8, 6]]])

In [115]:
#shape of array
a.shape

(1, 3, 3)

In [116]:
a.ndim

3

In [117]:
b

array([[[1, 2, 3],
        [3, 2, 1]],

       [[3, 4, 5],
        [5, 4, 3]],

       [[6, 7, 8],
        [8, 7, 6]]])

In [118]:
b.shape #3 dimentional, 2 rows, 3 columms

(3, 2, 3)

In [119]:
c= np.arange(9)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [120]:
#reshape an array
d=a.reshape(3,3)
d

array([[1, 2, 3],
       [2, 4, 5],
       [7, 8, 6]])

In [121]:
np.reshape(a, newshape=(1,9), order='C')

array([[1, 2, 3, 2, 4, 5, 7, 8, 6]])

In [122]:
np.reshape(a, newshape=(1,9), order='F')

array([[1, 2, 7, 2, 4, 8, 3, 5, 6]])

## Convert 1D to 2D


In [123]:
e=np.array([1,2,3,4,5,6,7,8,9])
e

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
e.ndim

1

In [125]:
e.shape

(9,)

In [126]:
#change row wise axis/dimension
f=e[np.newaxis, :]
f

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [127]:
#change column wise axis/dimension
z=e[:, np.newaxis]
z

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [128]:
f.ndim

2

In [129]:
f.shape

(1, 9)

In [130]:
g=f.reshape(3,3)
g

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
g.ndim

2

In [132]:
g[0:1]

array([[1, 2, 3]])

In [133]:
g*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [134]:
g+6

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [135]:
g.sum()

45

In [136]:
g.mean()

5.0

In [137]:
g

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
g[g>5]

array([6, 7, 8, 9])

In [139]:
g[g<=7]

array([1, 2, 3, 4, 5, 6, 7])

In [140]:
g[g%2==0]

array([2, 4, 6, 8])