In [ ]:
import numpy as np

In [ ]:
import numpy as np
a=np.arange(6)
a2=a[np.newaxis, :]
a2.shape

In [ ]:
a=np.array([4,4,4,4,4])
a

In [ ]:
import numpy as array
a=np.array([2,4,6]) #1 dimentional
a

In [ ]:
type(a)

In [ ]:
#list of lists
b=np.array([[2,2,2],     #3 dimentional
          [2,2,2],
          [2,2,2]])
b

# 1-D Array:

## A ***vector*** is an array with a single dimension
### There's no difference between row and column vectors

In [ ]:
import numpy as np
a=np.array([3,4,5])
a

In [ ]:
#type
type(a)

numpy.ndarray

In [ ]:
#length
len(a)

3

In [10]:
#index
a[2]

5

In [11]:
a[0:]

array([3, 4, 5])

In [12]:
import numpy as np
a=np.array([3,7,11,15,19])
a

array([ 3,  7, 11, 15, 19])

In [13]:
#arrays with zeros with 3 elements
b=np.zeros(3)
b


array([0., 0., 0.])

In [14]:
#array with 1s with 5 elements
c=np.ones(5)
c

array([1., 1., 1., 1., 1.])

In [15]:
#empty array with 3 elements
d=np.empty(3)
d

array([0., 0., 0.])

In [16]:
#with range of element
e=np.arange(8)
e

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
#with specific range of elements
f=np.arange(3, 36)
f

In [ ]:
g=np.arange(3,36, 3)
g

In [ ]:
#linearly spaced arrays
h=np.linspace(0,15, num=6)
h

In [ ]:
#linearly spaced arrays
h=np.linspace(0,15, num=10)
h

In [ ]:
#specific data type arrays
i=np.ones(4, dtype=np.int64)
i

In [ ]:
j=np.zeros(7, dtype=np.float32)
j

# 2-D Array:

## A ***matrix*** refers to an array with two dimensions

In [ ]:
#an array with 2 axis/dimensions #(3 rows and 3 colums)

import numpy as np
b=np.array([[3,4,5],
           [3,4,5],
           [3,4,5]])
b

In [ ]:
type(b)

In [ ]:
len(b)    # 3 lists in variable b

In [ ]:
#index
b[0]

In [ ]:
b[0 :]

In [ ]:
a=np.zeros((4,3))
a

In [ ]:
b=np.ones((4,7))
b

In [ ]:
c= np.empty((3,4))
c

# 3-D or higher arrays:

## For 3-D or higher dimentional arrays, the term *Tensor* is also commonly used

In [ ]:
nested_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
               [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
a = np.array(nested_list)
a

In [ ]:
#making and reshaping a 3D array
b=np.arange(24).reshape(2,3,4)
b